name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Node.js modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: VSCE Packge
        run: npx vsce package

  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Node.js modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: VSCE Packge
        run: npx vsce package
